---
title: "data"
author: "Ang Sonam Sherpa"
date: "11/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(pdftables)
```


```{r}
# data from Nepali women in Politics (page 83)

# constituent assembly refers to the legislative parliament formed to write
# the final constitution. This was later named the legislative parliament.

electionhistory <- tibble(
  year = c(1959, 1986, 1991, 1999, 2008, 2013),
  type = c("parliamentary", "parliamentary", "parliamentary",
           "parliamentary and local bodies", "constituent assembly",
           "constituent assembly"),
  womencontesting = c(6, NA, NA, NA, NA, NA),
  totalelected = c(109, 140, 205, 205, 240, 240),
  womenelected = c(0, 3, 7, 23, 40, 10),
  localtotal = c(NA, NA, NA, 4146, NA, NA),
  localwomen = c(NA, NA, NA, 806, NA, NA)
)

```


```{r}
# data from women in politics (page 86 and 87)

# I initially converted the table from the pdf to an excel file using an online
# conversion tool and copied the relevant pages to a separate excel file, that
# I used.

local2017 <- read.csv("data/local2017.csv") %>%
  clean_names()

```


```{r}

# data from women in politics (page 86 and 87)

# I simply did that same as above.

elections2017 <- read.csv("data/elections2017.csv") %>%
  clean_names()

```


```{r}

# data from Women's Representation in Bureaucracy: Reservation Policy in Nepali
# Civil Service

# converted to an excel file online, and manually created a new one with the
# relevant datasets

bureaucracytype <- read.csv("data/ncstype.csv") %>%
  clean_names()

reservationproportion <- read.csv("data/ncsreservationproportion.csv") %>%
  clean_names()

levelhistory <- read.csv("data/ncslevelhistory.csv") %>%
  clean_names()

levelrecent <- read.csv("data/ncslevelrecent.csv") %>%
  clean_names()

ncstrend <- read.csv("data/ncstrend2007to2018.csv") %>%
  clean_names()

```


